recipe: default.v1
language: en
pipeline:
- name: SingleStepLLMCommandGenerator
  llm:
    model_group: openai-gpt-4
  flow_retrieval:
    active: false

policies:
- name: FlowPolicy
# - name: IntentlessPolicy
assistant_id: 20250325-175310-exothermic-wheat